default:
  tags:
    - armageddon

variables:
  PIP_PACKAGE_URL: "https://upload.pypi.org/legacy/"
  TWINE_USERNAME: __token__
  TWINE_PASSWORD: ${PYPI_TOKEN}

include:
  - ".gitlab/ci/base.yml"

.static_analysis_base:
  allow_failure: true