include:
  - project: "cdos-pub/pycode-quality"
    ref: "main"
    file:
      - ".gitlab/ci/static-analysis.yml"
      - ".gitlab/ci/pip.yml"

variables:
  PIP_EXTRA_INDEX_URL: https://forgemia.inra.fr/api/v4/projects/14431/packages/pypi/simple
  PACKAGE_INSTALL_EXTRAS: "[test]"

stages:
  - Static Analysis
  - Test
  - Pip

.static_analysis_base:
  allow_failure: false

Tests:
  extends: .static_analysis_with_pip_install
  stage: Test
  allow_failure: false
  script:
    - if [ ! -d "tests" ]; then echo "Directory `tests` not found in the repository. Please use `tests` directory to implement unit/functional tests!"; exit 1; fi
    - coverage run -m pytest --junitxml=report.xml -s
    - coverage report
    - coverage xml
    - coverage html
  coverage: '/^TOTAL.+?(\d+\%)$/'
  artifacts:
    paths:
      - htmlcov/
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
